config/routes.rb
CardApp::Application.routes.draw do

  root :to => "user#index"

  post 'user/add_card/:id' => 'user#add_card'
  post 'user/remove_card/:id' => 'user#remove_card'

  resources :mst_cards do
    collection do
      get 'search'
    end
  end

  

  devise_for :users
end

app/models/custom_user_card.rb
class CustomUserCard < UserCard
  attr_accessor :card_name, :mana, :card_type, :poto, :text, :card_img_path
end

app/models/mst_card.rb
class MstCard < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_card.rb
class UserCard < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mst_cards_controller.rb
class MstCardsController < ApplicationController

  # GET /mst_cards
  # GET /mst_cards.json
  def index
    @mst_cards = MstCard.all
  end

  def search
    search_name = params[:search]
    if (search_name[:search] === "search_by_name")
      @mst_cards = MstCard.where('card_name like ?', "%" + params[:card] + "%")
    elsif (search_name[:search] === "search_by_text")
      @mst_cards = MstCard.where('text like ?', "%" + params[:card] + "%")
    else
      @mst_cards = Array.new
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mst_card
      @mst_card = MstCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mst_card_params
      params.require(:mst_card).permit(:card_name, :mana, :card_type, :poto, :text)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    user_id = current_user.id unless current_user.nil?
    @view_models = Array.new

    #ユーザデータ取得
    card_group_no = 1
    user_cards = UserCard.where("user_id = ? and card_group_no = ?", user_id, card_group_no)
    return if user_cards.nil?

    #マスターデータ取得
    user_card_ids = Array.new
    user_cards.each do |user_card|
      user_card_ids << user_card.card_id
    end
    mst_cards = MstCard.find(user_card_ids)

    #表示用のモデル作成
    mst_cards.each do |mst_card|
      user_cards.each do |user_card|
        if (user_card.card_id == mst_card.id)
          view_model = CustomUserCard.new
          view_model.attributes = mst_card.attributes
          view_model.attributes = user_card.attributes
          @view_models << view_model
        end
      end
    end
  end

  #カードの所持数を増やして、jsonを返す
  def add_card
    mst_card = MstCard.find(params[:id])
    card_add_count = 1
    user_id = current_user.id
    card_group_no = 1

    #カードの所持数を更新
    @user_card = UserCard.find_by(:user_id => user_id, :card_id => mst_card.id, :card_group_no => card_group_no)
    if (@user_card.nil?)
      @user_card = UserCard.new(:user_id => user_id, :card_id => mst_card.id, :card_group_no => card_group_no, :count => card_add_count)
    else
      new_card_count = @user_card.count + card_add_count
      @user_card.count = new_card_count
    end
    @user_card.save!

    respond_to do |format|
      format.js
    end
  end

  #カードの所持数を減らして、jsonを返す
  def remove_card
    mst_card = MstCard.find(params[:id])
    card_add_count = -1
    user_id = current_user.id
    card_group_no = 1

    #カードの所持数を更新
    @user_card = UserCard.find_by(:user_id => user_id, :card_id => mst_card.id, :card_group_no => card_group_no)


    unless (@user_card.nil?)
      if (@user_card.count > 0)
        new_card_count = @user_card.count + card_add_count
        @user_card.count = new_card_count
        @user_card.save!
      else
        @user_card.destroy
      end
    end

    respond_to do |format|
      format.js
    end
  end

end

app/helpers/application_helper.rb
# coding: utf-8
module ApplicationHelper
  def hbr(str)
    h(str).gsub(/(¥r¥n?)|(¥n)/, "<br />").html_safe
  end

  def apply_img_and_hbr (str)
    str_br = h(str).gsub(/(¥r¥n?)|(¥n)/, "<br />")
    apply_mana_img(str_br).html_safe
  end

  def apply_mana_img (str)
    str.gsub('{1}', mana_img("1"))
       .gsub('{2}', mana_img("2"))
       .gsub('{3}', mana_img("3"))
       .gsub('{4}', mana_img("4"))
       .gsub('{5}', mana_img("5"))
       .gsub('{6}', mana_img("6"))
       .gsub('{7}', mana_img("7"))
       .gsub('{8}', mana_img("8"))
       .gsub('{9}', mana_img("9"))
       .gsub('{10}', mana_img("10"))
       .gsub(/{W}/, mana_img("W"))
       .gsub(/{G}/, mana_img("G"))
       .gsub(/{R}/, mana_img("R"))
       .gsub(/{B}/, mana_img("B"))
       .gsub(/{U}/, mana_img("U"))
       .gsub(/{X}/, mana_img("X"))
       .gsub(/{Tap}/, mana_img("Tap"))
  end

  def mana_img (word)
    options = {}
    options[:src] = "/images/#{word}.png"
    options[:alt] = "{#{word}}"
    options[:width] = options[:height] = "10px"
    tag("img", options)
  end
end

app/helpers/mst_cards_helper.rb
module MstCardsHelper
end

app/helpers/user/user_helper.rb
module User::UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CardApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">

            <p id='navbar-main'><%= link_to "Mtg Search", root_path, :class => 'navbar-link'  %></p>
            <p class="navbar-text pull-right">
                <% if user_signed_in? %>
                    Logged in as <strong><%= current_user.email %></strong>.
                    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
                    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                <% else %>
                    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
                    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
                <% end %>
            </p>
        </div>
    </div>
</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/mst_cards/_form.html.erb
<%= form_for(@mst_card) do |f| %>
  <% if @mst_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mst_card.errors.count, "error") %> prohibited this mst_card from being saved:</h2>

      <ul>
      <% @mst_card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :card_name %><br>
    <%= f.text_field :card_name %>
  </div>
  <div class="field">
    <%= f.label :mana %><br>
    <%= f.text_field :mana %>
  </div>
  <div class="field">
    <%= f.label :card_type %><br>
    <%= f.text_field :card_type %>
  </div>
  <div class="field">
    <%= f.label :poto %><br>
    <%= f.text_field :poto %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mst_cards/edit.html.erb
<h1>Editing mst_card</h1>

<%= render 'form' %>

<%= link_to 'Show', @mst_card %> |
<%= link_to 'Back', mst_cards_path %>

app/views/mst_cards/index.html.erb
<h1>Listing mst_cards</h1>

<table>
  <thead>
    <tr>
      <th>Card name</th>
      <th>Mana</th>
      <th>Type</th>
      <th>Poto</th>
      <th>Text</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @mst_cards.each do |mst_card| %>
      <tr>
        <td><%= mst_card.card_name %></td>
        <td><%= mst_card.mana %></td>
        <td><%= mst_card.poto %></td>
        <td><%= hbr mst_card.text %></td>
        <td><%= link_to 'Show', mst_card %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/mst_cards/new.html.erb
<h1>New mst_card</h1>

<%= render 'form' %>

<%= link_to 'Back', mst_cards_path %>

app/views/mst_cards/search.html.erb
<%= render 'share/search_card' %>

<% unless @mst_cards.empty? %>
    <%= render partial: 'share/card_list', locals: {view_models: @mst_cards} %>
<% end %>

app/views/mst_cards/search_do.html.erb
<h1>Listing mst_cards</h1>


<br>

app/views/mst_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Card name:</strong>
  <%= @mst_card.card_name %>
</p>

<p>
  <strong>Mana:</strong>
  <%= @mst_card.mana %>
</p>

<p>
  <strong>Type:</strong>
  <%= @mst_card.card_type %>
</p>

<p>
  <strong>Poto:</strong>
  <%= @mst_card.poto %>
</p>

<p>
  <strong>Text:</strong>
  <%= @mst_card.text %>
</p>

<%= link_to 'Edit', edit_mst_card_path(@mst_card) %> |
<%= link_to 'Back', mst_cards_path %>

app/views/share/_card_list.html.erb
<% view_models.each_with_index do |card, index| %>
    <% if index % 4 == 0 %><ul class="card_line"><% end %>
    <li id="card_<%= card.respond_to?(:card_id) ? card.card_id : card.id %>" class="card">
        <p class="card_name"><small><%= card.card_name %></small></p>
        <span class="mana"><%= apply_img_and_hbr(card.mana) %></span>
        <span class="card_poto"><%= card.poto %></span>
        <div class="card_img"><%= image_tag('items' + card.card_img_path) %></div>
        <p class="card_text"><small><%= apply_img_and_hbr(card.text) %></small></p>
        <% if card.respond_to? :count %>
            <p class="card_count_with_mai"><span class="card_count"><%= card.count %></span>枚</p>
            <ul>
                <li class="count_up_btn"><%= button_to "増やす",  {:controller => "user", :action => "add_card", :id => card.card_id}, {:method => "POST", :remote => true} %></li>
                <li><%= button_to "減らす",  {:controller => "user", :action => "remove_card", :id => card.card_id}, {:method => "POST", :remote => true, :class => "delete_btn"} %></li>
            </ul>
        <% else %>
            <% if user_signed_in? %>
                <p class="regist_card_btn"><%= button_to "デッキに追加",  {:controller => "user", :action => "add_card", :id => card.id}, {:method => "POST", :remote => true} %></p>
            <% end %>
        <% end %>
    </li>
    <% if index % 4 == 3 %></ul><% end %>
<% end %>

app/views/share/_search_card.html.erb
<div class="search_form">
    <%= form_tag({:controller => 'mst_cards', :action => 'search'}, {:method => "GET" }) do %>
        <%= select(:search, :search, [["カード名で検索", "search_by_name"], ["カードの説明から検索", "search_by_text"]])%>
        <%= text_field_tag('card', '', {:size => 30}) %>
        <%= submit_tag('検索') %>
    <% end %>
</div>

app/views/user/add_card.js.erb
var dom = $(".card_count", "#card_<%= @user_card.card_id %>")
var val = dom.text()
val = Number(val) || 0
val = val+1
if (val === 1) {
    $(".delete_btn", "#card_<%= @user_card.card_id %>").val("減らす")
}
dom.text(val)

app/views/user/index.html.erb
<% if @view_models.empty? %>
    <% if user_signed_in? %>
        <%= render 'share/search_card' %>
    <% else %>
        <%= render 'share/search_card' %>
    <% end %>

<% else %>
    <%= render 'share/search_card' %>
    <%= render partial: 'share/card_list', locals: {view_models: @view_models} %>

<% end %>

app/views/user/remove_card.js.erb
var dom = $(".card_count", "#card_<%= @user_card.card_id %>")
var val = dom.text()
val = Number(val) || 0
if (val > 0) {
    val = val-1
    dom.text(val)
    if (val === 0) {
        $(".delete_btn", "#card_<%= @user_card.card_id %>").val("削除する")
    }
} else {
    $("#card_<%= @user_card.card_id %>").css("display", "none")
}